"""
Markdown to PDF Converter
Converts markdown files to PDF format with proper styling
Uses alternative libraries for better Windows compatibility
"""

import os
import sys
from pathlib import Path
import markdown
import pdfkit
from markdown.extensions import tables, fenced_code, toc

def convert_md_to_pdf(md_file_path: str, output_path: str = None) -> str:
    """
    Convert a markdown file to PDF with professional styling.
    
    Args:
        md_file_path: Path to the markdown file
        output_path: Optional output path for PDF (defaults to same name as md file)
    
    Returns:
        Path to the generated PDF file
    """
    try:
        # Read markdown file
        with open(md_file_path, 'r', encoding='utf-8') as f:
            md_content = f.read()
        
        # Convert markdown to HTML
        html_content = markdown.markdown(
            md_content, 
            extensions=['tables', 'fenced_code', 'toc']
        )
        
        # Create styled HTML with CSS
        styled_html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>Market Research Report</title>
            <style>
                body {{
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                    line-height: 1.6;
                    color: #333;
                    max-width: 100%;
                    margin: 0;
                    padding: 20px;
                }}
                
                h1 {{
                    color: #2c3e50;
                    border-bottom: 3px solid #3498db;
                    padding-bottom: 10px;
                }}
                
                h2 {{
                    color: #34495e;
                    border-bottom: 2px solid #ecf0f1;
                    padding-bottom: 8px;
                    margin-top: 30px;
                }}
                
                h3 {{
                    color: #2c3e50;
                    margin-top: 25px;
                }}
                
                h4 {{
                    color: #34495e;
                    margin-top: 20px;
                }}
                
                p {{
                    margin-bottom: 12px;
                    text-align: justify;
                }}
                
                ul, ol {{
                    margin-bottom: 15px;
                    padding-left: 25px;
                }}
                
                li {{
                    margin-bottom: 5px;
                }}
                
                table {{
                    width: 100%;
                    border-collapse: collapse;
                    margin: 20px 0;
                }}
                
                th, td {{
                    border: 1px solid #ddd;
                    padding: 12px;
                    text-align: left;
                }}
                
                th {{
                    background-color: #f8f9fa;
                    font-weight: bold;
                }}
                
                code {{
                    background-color: #f4f4f4;
                    padding: 2px 4px;
                    border-radius: 3px;
                    font-family: 'Courier New', monospace;
                }}
                
                pre {{
                    background-color: #f8f9fa;
                    padding: 15px;
                    border-radius: 5px;
                    border-left: 4px solid #3498db;
                    overflow-x: auto;
                }}
                
                pre code {{
                    background-color: transparent;
                    padding: 0;
                }}
                
                blockquote {{
                    border-left: 4px solid #3498db;
                    margin: 20px 0;
                    padding: 10px 20px;
                    background-color: #f8f9fa;
                    font-style: italic;
                }}
                
                .highlight {{
                    background-color: #fff3cd;
                    padding: 15px;
                    border-radius: 5px;
                    border-left: 4px solid #ffc107;
                    margin: 15px 0;
                }}
                
                .footer {{
                    margin-top: 50px;
                    padding-top: 20px;
                    border-top: 1px solid #ecf0f1;
                    font-size: 0.9em;
                    color: #7f8c8d;
                    text-align: center;
                }}
            </style>
        </head>
        <body>
            {html_content}
            <div class="footer">
                <p>Generated by Multi-Agent Market Research System</p>
            </div>
        </body>
        </html>
        """
        
        # Generate output path if not provided
        if output_path is None:
            md_path = Path(md_file_path)
            output_path = md_path.with_suffix('.pdf')
        
        # Convert HTML to PDF using pdfkit (more Windows-friendly)
        options = {
            'page-size': 'A4',
            'margin-top': '2cm',
            'margin-right': '2cm',
            'margin-bottom': '2cm',
            'margin-left': '2cm',
            'encoding': "UTF-8",
            'no-outline': None,
            'enable-local-file-access': None
        }
        
        pdfkit.from_string(styled_html, output_path, options=options)
        
        print(f"✅ PDF generated successfully: {output_path}")
        return str(output_path)
        
    except Exception as e:
        print(f"❌ Error converting to PDF: {e}")
        raise

def test_conversion():
    """Test the PDF conversion with a sample markdown file."""
    # Create a sample markdown file for testing
    sample_md = """# Market Research Report

## Executive Summary
This is a test report to verify PDF conversion functionality.

### Key Findings
- Finding 1: Test data point
- Finding 2: Another test data point

## Market Analysis
The market shows strong growth potential with several key trends:

1. **Trend 1**: Description of trend
2. **Trend 2**: Another trend description

### Competitive Landscape
| Company | Market Share | Key Strengths |
|---------|--------------|---------------|
| Company A | 25% | Strong brand |
| Company B | 20% | Innovation |

## AI Use Cases

### Use Case 1: Predictive Analytics
**Problem**: Need for better forecasting
**Solution**: Implement ML models
**Impact**: 15% efficiency improvement

## Conclusion
This test demonstrates successful PDF conversion with proper formatting.
"""
    
    # Write sample file
    test_file = "test_report.md"
    with open(test_file, 'w', encoding='utf-8') as f:
        f.write(sample_md)
    
    print("📝 Created test markdown file")
    
    # Convert to PDF
    try:
        pdf_path = convert_md_to_pdf(test_file)
        print(f"✅ Test conversion successful!")
        print(f"📄 PDF saved at: {pdf_path}")
        
        # Clean up test file
        os.remove(test_file)
        print("🧹 Cleaned up test file")
        
        return True
    except Exception as e:
        print(f"❌ Test conversion failed: {e}")
        return False

if __name__ == "__main__":
    print("🧪 Testing PDF conversion...")
    success = test_conversion()
    
    if success:
        print("\n✅ PDF conversion test PASSED!")
        print("Ready to integrate into Streamlit app.")
    else:
        print("\n❌ PDF conversion test FAILED!")
        print("Please check dependencies and try again.")